const data = {
  username: 'Ada',
  minimumBid: '$100',
  auctionEndsIn: '2 hours',
  usernameFull: 'Ada Lovelace',
  approxBid: '$150',
  auctionEndsInProper: 'Oct 18, 2025 5:30 PM',
}

export const TABLE_DATA = [
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Ada',
    minimumBid: '$100',
    auctionEndsIn: '2 hours',
    usernameFull: 'Ada Lovelace',
    approxBid: '$150',
    auctionEndsInProper: 'Oct 18, 2025 5:30 PM',
  },
  {
    username: 'Grace',
    minimumBid: '$250',
    auctionEndsIn: '5 hours',
    usernameFull: 'Grace Hopper',
    approxBid: '$300',
    auctionEndsInProper: 'Oct 18, 2025 8:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Ada',
    minimumBid: '$100',
    auctionEndsIn: '2 hours',
    usernameFull: 'Ada Lovelace',
    approxBid: '$150',
    auctionEndsInProper: 'Oct 18, 2025 5:30 PM',
  },
  {
    username: 'Grace',
    minimumBid: '$250',
    auctionEndsIn: '5 hours',
    usernameFull: 'Grace Hopper',
    approxBid: '$300',
    auctionEndsInProper: 'Oct 18, 2025 8:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Ada',
    minimumBid: '$100',
    auctionEndsIn: '2 hours',
    usernameFull: 'Ada Lovelace',
    approxBid: '$150',
    auctionEndsInProper: 'Oct 18, 2025 5:30 PM',
  },
  {
    username: 'Grace',
    minimumBid: '$250',
    auctionEndsIn: '5 hours',
    usernameFull: 'Grace Hopper',
    approxBid: '$300',
    auctionEndsInProper: 'Oct 18, 2025 8:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
  {
    username: 'Alan',
    minimumBid: '$500',
    auctionEndsIn: '1 day',
    usernameFull: 'Alan Turing',
    approxBid: '$650',
    auctionEndsInProper: 'Oct 19, 2025 3:30 PM',
  },
]
